services:
  application:
    image: dev/lisbag-server/application:1.0
    container_name: aplication_lisbag_server_dev
    build: 
      context: ./
      dockerfile: ./infra/docker-images/application/Dockerfile.dev
    volumes:
      - ./src:/src
  
  relational-db:
    image: dev/lisbag-server/relational-db:1.0
    container_name: relational_db_lisbag_server_dev
    build: 
      context: ./
      dockerfile: ./infra/docker-images/postgres/Dockerfile.dev
    ports:
      - 5432:5432
    volumes:
      - ./infra/docker-images/postgres/dev-data:/var/lib/postgresql/data

  reverse-proxy:
    image: dev/lisbag-server/reverse-proxy:1.0
    container_name: reverse_proxy_lisbag_server_dev
    build: 
      context: ./
      dockerfile: ./infra/docker-images/nginx/Dockerfile.dev
    ports:
      - 80:80

  application-unit-test:
    image: dev/lisbag-server/application-unit-test:1.0
    container_name: application_unit_test_lisbag_server_dev
    build:
      context: ./
      dockerfile: ./infra/docker-images/tests/Dockerfile.unit
    profiles:
      - unitTests
  
  application-integration-test:
    image: dev/lisbag-server/application-integration-test:1.0
    container_name: application_integration_test_lisbag_server_dev
    build:
      context: ./
      dockerfile: ./infra/docker-images/tests/Dockerfile.integration
    profiles:
      - integrationTests

networks:
  default:
    name: lisbag-server-dev-network