FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app/test

COPY ./tests/LisbagServerTests.sln .
COPY ./tests/unit .
RUN  dotnet restore

ENTRYPOINT [ "dotnet", "test", "unit/LisbagServer.test.unit.csproj" ]