// <auto-generated />
using System;
using LisbagServer.Infra.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LisbagServer.Infra.Dal.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20230329011540_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profile")
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LisbagServer.Domain.Entities.ProfileAggregate.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PostalCode")
                        .HasMaxLength(8)
                        .HasColumnType("integer")
                        .HasColumnName("postal_code");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.Property<int?>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_address");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_address_profile_id");

                    b.ToTable("address", "profile");
                });

            modelBuilder.Entity("LisbagServer.Domain.Entities.ProfileAggregate.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("InternationalAreaCode")
                        .HasMaxLength(2)
                        .HasColumnType("integer")
                        .HasColumnName("international_area_code");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<int>("Number")
                        .HasMaxLength(9)
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Prefix")
                        .HasMaxLength(2)
                        .HasColumnType("integer")
                        .HasColumnName("prefix");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.HasKey("Id")
                        .HasName("pk_phone");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_phone_profile_id");

                    b.ToTable("phone", "profile");
                });

            modelBuilder.Entity("LisbagServer.Domain.Entities.ProfileAggregate.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("pk_profile");

                    b.ToTable("profile", "profile");
                });

            modelBuilder.Entity("LisbagServer.Domain.Entities.ProfileAggregate.Address", b =>
                {
                    b.HasOne("LisbagServer.Domain.Entities.ProfileAggregate.Profile", null)
                        .WithMany("Addresses")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("fk_address_profile_profile_id");
                });

            modelBuilder.Entity("LisbagServer.Domain.Entities.ProfileAggregate.Phone", b =>
                {
                    b.HasOne("LisbagServer.Domain.Entities.ProfileAggregate.Profile", null)
                        .WithMany("Phones")
                        .HasForeignKey("ProfileId")
                        .HasConstraintName("fk_phone_profile_profile_id");
                });

            modelBuilder.Entity("LisbagServer.Domain.Entities.ProfileAggregate.Profile", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
